name: CI
on:
  push:
    branches:
      - development
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v6
      - name: set user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      # use node module caching
      - uses: actions/cache@v5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install packages
        run: corepack enable && yarn install --immutable
      - name: check format
        run: yarn formatAllCheck
      - name: lint
        run: yarn lint
